import fs from "node:fs";
import path from "node:path";

const variants = ["outline", "filled"];
const sourceExtensions = new Set([".ts", ".tsx", ".js", ".jsx", ".mdx"]);
const ignoredDirectories = new Set([
  ".git",
  "dist",
  "node_modules",
  ".pnpm-store",
]);

const tablerRoot = path.resolve(process.cwd(), "theme/tabler");
const typesFilePath = path.join(tablerRoot, "types.ts");
const usedIconsFilePath = path.join(tablerRoot, "used-icons.ts");
const safelistFilePath = path.join(tablerRoot, "safelist.ts");

const toPascalCase = (str) =>
  str
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

const readIconNames = (variant) =>
  fs
    .readdirSync(path.join(tablerRoot, variant))
    .filter((file) => file.endsWith(".svg"))
    .map((file) => path.basename(file, ".svg"))
    .sort((a, b) => a.localeCompare(b));

const walkSourceFiles = (directory, files = []) => {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (ignoredDirectories.has(entry.name)) {
      continue;
    }

    const entryPath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      walkSourceFiles(entryPath, files);
      continue;
    }

    if (!sourceExtensions.has(path.extname(entry.name))) {
      continue;
    }

    if (
      entryPath === typesFilePath ||
      entryPath === usedIconsFilePath ||
      entryPath.endsWith(path.join("theme", "tabler", "icons.ts"))
    ) {
      continue;
    }

    files.push(entryPath);
  }

  return files;
};

const toIconUsage = (icon, variant = "outline") => ({ icon, variant });

const extractSafelist = (contents) =>
  Array.from(contents.matchAll(/["']([a-z0-9][a-z0-9-]*)["']/g), ([, icon]) =>
    toIconUsage(icon.trim()),
  );

const extractUsedIcons = (contents) => {
  const icons = [];

  for (const [, props] of contents.matchAll(
    /<(?:TablerIcon|Ornament)\b([^>]*)>/g,
  )) {
    const icon = props.match(/\bicon=["']([^"']+)["']/)?.[1]?.trim();

    if (!icon) {
      continue;
    }

    const variant =
      props.match(/\bvariant=["'](outline|filled)["']/)?.[1] ?? "outline";
    icons.push(toIconUsage(icon, variant));
  }

  for (const [, icon] of contents.matchAll(/\bicon:\s*["']([^"']+)["']/g)) {
    icons.push(toIconUsage(icon.trim()));
  }

  return icons;
};

const writeIfChanged = (filePath, contents) => {
  if (
    fs.existsSync(filePath) &&
    fs.readFileSync(filePath, "utf8") === contents
  ) {
    return false;
  }

  fs.writeFileSync(filePath, contents);
  return true;
};

const createTypesFile = (allIconNames) => {
  const names = allIconNames
    .map((name) => `  | ${JSON.stringify(name)}`)
    .join("\n");

  return `/* This file is generated by ./jit.mjs. */\n\nexport type TablerIconVariant = "outline" | "filled";\n\nexport type TablerIconName =\n${names};\n\nexport const tablerIconNames = [\n${allIconNames.map((name) => `  ${JSON.stringify(name)},`).join("\n")}\n] as const;\n`;
};

const createUsedIconsFile = (usedByVariant) => {
  const importStatements = [];
  const variantMaps = [];

  for (const variant of variants) {
    const entries = Array.from(usedByVariant[variant]).sort((a, b) =>
      a.localeCompare(b),
    );

    const mapEntries = entries.map((iconName) => {
      const variableName = `${variant}Icon${toPascalCase(iconName)}`;
      importStatements.push(
        `import ${variableName} from "./${variant}/${iconName}.svg?react";`,
      );

      return `    ${JSON.stringify(iconName)}: ${variableName},`;
    });

    variantMaps.push(`  ${variant}: {\n${mapEntries.join("\n")}\n  },`);
  }

  return `/* This file is generated by ./jit.mjs. */\n\n${importStatements.join("\n")}\n\nexport const usedTablerIcons = {\n${variantMaps.join("\n")}\n} as const;\n`;
};

export function generateTablerIcons() {
  const namesByVariant = Object.fromEntries(
    variants.map((variant) => [variant, new Set(readIconNames(variant))]),
  );
  const allIconNames = Array.from(
    new Set(variants.flatMap((variant) => Array.from(namesByVariant[variant]))),
  ).sort((a, b) => a.localeCompare(b));

  const usedIcons = [];
  for (const filePath of walkSourceFiles(process.cwd())) {
    const contents = fs.readFileSync(filePath, "utf8");
    const extracted =
      filePath === safelistFilePath
        ? extractSafelist(contents)
        : extractUsedIcons(contents);

    for (const usage of extracted) {
      if (allIconNames.includes(usage.icon)) {
        usedIcons.push(usage);
      }
    }
  }

  const usedByVariant = Object.fromEntries(
    variants.map((variant) => [variant, new Set()]),
  );

  for (const { icon, variant } of usedIcons) {
    const resolvedVariant = namesByVariant[variant].has(icon)
      ? variant
      : namesByVariant.outline.has(icon)
        ? "outline"
        : "filled";
    usedByVariant[resolvedVariant].add(icon);
  }

  const changed = [
    writeIfChanged(typesFilePath, createTypesFile(allIconNames)),
    writeIfChanged(usedIconsFilePath, createUsedIconsFile(usedByVariant)),
  ];

  return changed.some(Boolean);
}

export function tablerIconsPlugin() {
  return {
    name: "tabler-icons-jit",
    buildStart() {
      generateTablerIcons();
    },
    configureServer(server) {
      generateTablerIcons();

      server.watcher.on("change", (filePath) => {
        if (!sourceExtensions.has(path.extname(filePath))) {
          return;
        }

        if (generateTablerIcons()) {
          server.moduleGraph.invalidateAll();
        }
      });
    },
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generateTablerIcons();
}
